# This is a basic workflow that is manually triggered, cuz I dont have enaf resource to run this code daily :((( plz, give me a coffee

name: Manual trigger workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest
    continue-on-error: true  # Allow job to continue despite failures
    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 17
      uses: actions/setup-java@v2
      with:
        java-version: '17'
        distribution: 'adopt'
        cache: maven
    - name: Run test with Serenity framework using command line
      run: mvn test
    - name: Archive reports  and push report to an uploader in order to download later
      uses: actions/upload-artifact@v3
      with:
        name: karate-report
        path: target/karate-reports
